notifications:
  email: false

language: node_js

node_js:
  - '4.2.4'

branches:
  only:
    - master

before_script: "(npm run-script selenium-server & npm run-script local-webserver) 2>&1 >/dev/null &"

script: "sleep 10 && NODE_ENV=build ./test/run.js"
